### PR TITLE
Add meta tags, site properties, and update resources

### PR DESCRIPTION
**Pull request by Astro36**
# Added 
- site.keywords
- site.owner.telegram
- twitter meta tags
- open graph meta tags

# Changed
- the format of title (ex. "Categories | Leonids")

# Updated
- jquery 3.2.1
- chart.js 2.6.0,
- font awesome 4.7.0

### CODE REVIEW

**Comment by renyuanz** [comment]
Nice work! Thanks for the PR, I'll test it locally coz you updated some libraries and config file. Normally, I'll merge it this weekend if everything works well. 👍

**Comment by Astro36** [comment]
Did you have any problems on testing the commits?

**Comment by renyuanz** [comment]
Sorry man, I forgot to get it merged. I've tested and it's fine. Thanks for the PR!

**Comment by Astro36** [comment]
thanks!

**Pull request merged**
